### ISSUE TITLE
Fork pybind11 so CyberReboot owns a copy

### ISSUE THREAD

**Issue by AlexanderTitus** [CyberReboot/pySEAL#2]
The pySEAL docker image currently clones a public repository for pybind11
`git clone https://github.com/pybind/pybind11.git`

I would like to request that CyberReboot forks pybind11 so we can point the docker image to our own hosted repo to prevent our build from breaking if they update the software without our knowledge. 

Thanks!

**Comment by cglewis** [comment]
@AlexanderTitus why not do a `git checkout` to the specific commit that works for what you need, that we don't have to maintain yet another fork?

**Comment by AlexanderTitus** [comment]
@cglewis I'll do that.
